from src.modules.servermenu.menu                   import servermenu
from src.modules.tokenmenu.menu                    import tokenmenu
from src.modules.spammingmenu.menu                 import spammingmenu
from src.modules.bypassmenu.menu                   import bypassmenu
from src.modules.vcmenu.menu                       import vcmenu
from src.modules.webhookmenu.menu                  import webhookmenu
from src.modules.adminmenu.menu                    import adminmenu
from src.modules.proxymenu.menu                    import proxymenu
from src.modules.exploitmenu.menu                  import exploitmenu
from src.modules.massreportmenu.menu               import massreportmenu
from src.modules.funnymenu.menu                    import funnymenu
from src.modules.scrapingmenu.menu                 import scrapingmenu
from src.modules.suppliers                         import suppliers